// Reverse-proxies www.nuttakitkundum.com/badugi/* to the Vercel deployment.
// Other paths get a placeholder root page.
//
// Pair this with `basePath: "/badugi"` in next.config.ts so all asset URLs
// generated by Next.js are already prefixed with /badugi.

// Update this to match your Vercel production URL.
const ORIGIN = "https://badugi-tutorial.vercel.app";

export default {
  async fetch(request) {
    const url = new URL(request.url);

    if (url.pathname === "/badugi" || url.pathname.startsWith("/badugi/")) {
      const target = ORIGIN + url.pathname + url.search;
      const proxied = await fetch(target, {
        method: request.method,
        headers: request.headers,
        body: ["GET", "HEAD"].includes(request.method) ? undefined : request.body,
        redirect: "manual",
      });
      return proxied;
    }

    return new Response(rootHtml(), {
      status: 200,
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  },
};

function rootHtml() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>nuttakitkundum.com</title>
  <style>
    body{font-family:ui-sans-serif,system-ui,sans-serif;background:#03101e;color:#e2e8f0;
         display:grid;place-items:center;min-height:100vh;margin:0;text-align:center;padding:2rem}
    a{color:#7dd3fc;text-decoration:none;border-bottom:1px solid rgba(125,211,252,.4)}
    a:hover{color:#fff;border-bottom-color:#fff}
  </style>
</head>
<body>
  <main>
    <h1>nuttakitkundum.com</h1>
    <p>Site under construction.</p>
    <p><a href="/badugi">→ Badugi tutorial</a></p>
  </main>
</body>
</html>`;
}
